### ISSUE TITLE
Problem with default User Model

### ISSUE THREAD

**Issue by hieunv95** [devemio/elasticsearch-eloquent#23]
I rewrote default User Model extends ElasticsearchModel:
`<?php

namespace App;

use Illuminate\Notifications\Notifiable;
//use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use App\ElasticsearchModel as Model;
//use Laravel\Scout\Searchable;

class User extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword, Notifiable;

    protected static $_index = 'laravel';
    protected static $_type = 'user';

    // public $name;
    // public $email;
    // public $password;
    // public $remember_token;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
`
When I ran App\User::search($query)->get();, I got this error:
Illuminate\Contracts\Container\BindingResolutionException with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $retries ]] in class Elasticsearch\Transport'

**Comment by BirdyUK** [comment]
@hieuUET2395 - Im having the same issue, Did you resolve this mate?

**Comment by hieuUET2395** [comment]
I haven't found solution. I use different package with Scout support:
https://github.com/jeylabs/laravel-scout-elastic
